# Generated by Django 3.2.25 on 2024-09-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20240925_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
    ]
