# Generated by Django 3.2.25 on 2024-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_income_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('utilities', 'Коммунальные платежи'), ('communication', 'Мобильная связь, интернет, телевидение'), ('loan', 'Оплата кредита'), ('car', 'Автомобиль'), ('food', 'Продукты питания'), ('cleaning', 'Уборка'), ('other', 'Прочие расходы')], max_length=20, verbose_name='Категория'),
        ),
    ]
