# Generated by Django 3.2.25 on 2024-10-01 05:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0008_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100, verbose_name='Наименование автомобиля')),
                ('mileage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Пробег')),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма расхода')),
                ('category', models.CharField(default='transport', editable=False, max_length=20)),
                ('subcategory', models.CharField(choices=[('car_service', 'Расходы на ремонт и ТО автомобиля (без запчастей)'), ('spare_parts', 'Покупка запчастей и расходных материалов'), ('atocosmetics', 'Автокосметика'), ('carwash', 'Мойка и уборка автомобиля'), ('other_for_car', 'Другие расходы на автомобиль')], max_length=20, verbose_name='Подкатегория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расход на автомобиль',
                'verbose_name_plural': 'Расходы на автомобиль',
            },
        ),
    ]
