# Generated by Django 3.2.25 on 2024-10-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_carexpense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carexpense',
            options={},
        ),
        migrations.AddField(
            model_name='carexpense',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_expense', to='accounting.expense'),
        ),
        migrations.AlterField(
            model_name='carexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carexpense',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carexpense',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carexpense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carexpense',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carexpense',
            name='subcategory',
            field=models.CharField(max_length=100),
        ),
    ]
